services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongo
      - data_processing_service
    networks:
      - app-network
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    env_file:
      - .env

  data_processing_service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "5001:5000"
    networks:
      - app-network
    env_file:
      - .env
  

volumes:
  mongo-data:

networks:
  app-network: